### ISSUE TITLE
Unable to install with anaconda on windows

### ISSUE THREAD

**Issue by raziel2701** [paruch-group/xrdtools#1]
Running anaconda (python 3) on windows pc I am unable to install xrdtools:

Collecting xrdtools
  Using cached xrdtools-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Raziel\AppData\Local\Temp\pip-build-ftqkzncr\xrdtools\setup
.py", line 4, in <module>
        from xrdtools import __version__, __name__ as package_name
      File "C:\Users\Raziel\AppData\Local\Temp\pip-build-ftqkzncr\xrdtools\xrdto
ols\__init__.py", line 1, in <module>
        from io import read_xrdml
    ImportError: cannot import name 'read_xrdml'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Raziel\A
ppData\Local\Temp\pip-build-ftqkzncr\xrdtools

Is this supposed to run on python3 or is there something else going on?

**Comment by bziegler** [comment]
Thanks for the issue report. I fixed the imports to work with python3. It should work now.

**Comment by raziel2701** [comment]
Confirmed it is working now. Thank you!
